### PR TITLE
Cosmetic update: Simplified the header for the trial grid

### PR DESCRIPTION
**Pull request by adambraimbridge**
! This PR still needs QA testing for all browsers. !

As reported by @wheresrhys here: https://financialtimes.slack.com/files/rhys.evans/F20AWUXNF/pasted_image_at_2016_08_11_10_46_am.png

Cosmetic update: Simplified the header for the trial grid so it's more consistent and doesn't break padding.

Full width:
image

Narrow width:
image

### CODE REVIEW

**Comment by tgabe** [comment]
@ifyio , @tavvy - can one of your approve this please?

**Comment by Purvi22Patel** [comment]
@ifyio @tgabe @tavvy - has this been done? I'm catching up on messages so apols if it has ... :)

**Comment by adambraimbridge** [comment]
I've tested this on my mac in Chrome Version 52.0.2743.116 (64-bit)

**Comment by lc512k** [comment]
Sorry we dropped the ball on this one, @adambraimbridge :( I'm closing it for now, though, considering we're not going to update this barrier anymore until it gets a proper facelift later this quarter.

**Pull request closed without merging**
